name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

env:
  CACHE_REPO: ghcr.io/cubismod/grafana-backup-tool/cache
  REPO: ghcr.io/cubismod/grafana-backup-tool

on:
  push:
    branches: ["master"]
  pull_request:
  merge_group:

jobs:
  build-master:
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: login to ghcr
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: build and push
        uses: docker/build-push-action@ee4ca427a2f43b6a16632044ca514c076267da23 # v6
        with:
          context: .
          push: true
          tags: ${{ env.REPO }}:${{ github.sha }},${{ env.REPO }}:latest,${{ env.REPO }}:dev-latest
          cache-from: type=registry,ref=${{ env.CACHE_REPO }}
          cache-to: type=registry,ref=${{ env.CACHE_REPO }},mode=max
  pr-check:
    if: startsWith(github.ref, 'refs/pull/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: login to ghcr
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3
      - name: build and push
        uses: docker/build-push-action@ee4ca427a2f43b6a16632044ca514c076267da23 # v6
        with:
          context: .
          push: true
          tags: ${{ env.REPO }}:${{ github.sha }},${{ env.REPO }}:dev-latest
          cache-from: type=registry,ref=${{ env.CACHE_REPO }}
          cache-to: type=registry,ref=${{ env.CACHE_REPO }},mode=max
